development:
  adapter: redis
  url: <%= ENV["CABLE_REDIS_URL"] || ENV["REDIS_URL"] || "redis://localhost:6379/1" %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV["CABLE_REDIS_URL"] || ENV["REDIS_URL"] || "redis://localhost:6379/1" %>
  channel_prefix: tern_staging
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

production:
  adapter: redis
  url: <%= ENV["CABLE_REDIS_URL"] || ENV["REDIS_URL"] || "redis://localhost:6379/1" %>
  channel_prefix: tern_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
